config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get '/resume', to: 'pages#home'
  get '/interests', to: 'pages#home'
  get '/specialties', to: 'pages#home'
  get '/highlights', to: 'pages#home'
  get '/contact', to: 'pages#home'
  get '/blog', to: 'pages#home'
  get '/blog/:slug', as: :blog_post, to: 'pages#home'
  get '/subscribers/:id/edit', as: :subscribers_unsubscribe, to: 'pages#home'
  get '/text-formatter', to: 'pages#home'

  # Authentication routes
  devise_for :users, skip: [:registrations], controllers: {
    sessions: 'users/sessions',
    unlocks: 'users/unlocks',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    # omniauth_callbacks: 'users/omniauth_callbacks',
  }
  devise_scope :user do
    get '/profile', to: "users/admin#home", as: :profile
    get '/users/edit', to: "users/registrations#edit", as: :edit_user_registration
    patch '/users/id', to: "users/registrations#update", as: :user_registration
  end

  # Define external URLs
  direct :github do
    "https://github.com/ccentrella"
  end

  direct :linkedin do
    "https://linkedin.com/in/ccentrella/"
  end

  direct :photos do
    "https://lightroom.adobe.com/gallery/35c62e7ff3ce476f9ae5b07994eb6f15"
  end
  
  # Define routes using old post API.
  # This is a temporary solution to administer the admin backend until we convert everything to React
  resources :posts, path: '/posts', only: [:new, :create, :edit, :update, :destroy], param: :slug do
    get '/index/admin', on: :collection, as: 'admin_index', to: "posts#admin_index"
  end 

  # Define routes using new APIs
  get '/feed', to: "api/v1/posts#index", format: 'rss'
  namespace :api do
    namespace :v1 do
      resources :posts, path: '/blog', only: [:index, :show], param: :slug do
        get '/latest_article', on: :collection, to: "posts#latest_article"
      end 
      resources :contact, path: '/contact', only: [:create]
      resources :subscribers, only: [:create, :edit, :destroy]
    end
  end
  get '/blog/feed', to: "api/v1/posts#index", format: 'rss'

  # Define error paths
  match '/404', via: :all, to: 'errors#not_found'
  match '/500', via: :all, to: 'errors#server_error'
end

app/views/layouts/_meta.html.erb
<!-- HTML Meta Tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="author" content="Chris Centrella">
<meta name="description" content="10 years of coding experience, with extensive knowledge of frontend and backend. Exceptional debugging and problem solving using Root Cause Analysis (RCA).">
<meta name="th">

<!-- Facebook Meta Tags --> 
<meta property="og:url" content="https://chriscentrella.com">
<meta property="og:type" content="website">
<meta property="og:title" content="Welcome to Chris Centrella's Portfolio">
<meta property="og:description" content="10 years of coding experience, with extensive knowledge of frontend and backend. Exceptional debugging and problem solving using Root Cause Analysis (RCA).">
<meta property="og:image" content="https://chriscentrella.com/assets/thumbnail.png">

<!-- Twitter Meta Tags -->
<meta name="twitter:card" content="summary_large_image">
<meta property="twitter:domain" content="chriscentrella.com">
<meta property="twitter:url" content="https://chriscentrella.com">
<meta name="twitter:title" content="Welcome to Chris Centrella's Portfolio">
<meta name="twitter:description" content="10 years of coding experience, with extensive knowledge of frontend and backend. Exceptional debugging and problem solving using Root Cause Analysis (RCA).">
<meta name="twitter:image" content="https://chriscentrella.com/assets/thumbnail.png">

<!-- Meta Tags Generated via https://opengraph.dev -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= full_title(yield (:title)) %></title>
    
    <%= render "layouts/meta" %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.png') %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= auto_discovery_link_tag :rss, blog_url(format: :rss) %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <% if !flash.empty? %>
      <div class="flash-container">
        <% flash.each do |message_type, message| %>
          <div class="flash flash-<%= message_type %>">
            <p><%= message %></p>
          </div>
        <% end %>
      </div>
      <br/>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/no-flash-header.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= full_title(yield (:title)) %></title>
    
    <%= render "layouts/meta" %>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path('favicon.png') %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= auto_discovery_link_tag :rss, blog_url(format: :rss) %>

  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/no-flash.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= full_title(yield (:title)) %></title>
    
    <%= render "layouts/meta" %>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path('favicon.png') %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= auto_discovery_link_tag :rss, blog_url(format: :rss) %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/react.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= full_title(yield (:title)) %></title>

    <%= render "layouts/meta" %>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.png') %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= auto_discovery_link_tag :rss, blog_url(format: :rss) %>

  </head>
  <body>
    <% if !flash.empty? %>
      <div class="flash-container">
        <% flash.each do |message_type, message| %>
          <div class="flash flash-<%= message_type %>"><p><%= message %></p></div>
        <% end %>
      </div>
      <br/>
      <br/>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/messages/new.html.erb
<% provide(:title, "Get in Touch") %>
<main>
  <h1>Get in Touch</h1>
  <p class="large">Thank you so much for reaching out to me! Because I’m still attending college I can’t make any promises, but I will do my best to respond as soon as possible. I look forward to getting back to you!</p>
  <p class="large">“The Lord, He is my strength and my song, and He has become my salvation. He is <em>my God</em>.”
    (Exodus 15:2)</p>
</main>
<%= form_with(model: @message, class: 'contact-form') do |f| %>
    <%= render 'shared/error_messages' %>

    <%= f.text_field :name, placeholder: 'Name', class: 'field' %>
    <br/>
    <%= f.email_field :email, placeholder: 'Email', class: 'field' %>
    <br/>
    <%= f.text_area :details, placeholder: 'Message', class: 'field field-message' %>
    <br/>

    <%= f.text_field :nickname, hint: 'Leave this field blank!', class: 'hidden' %>
    <%= f.submit 'Send Message', class: 'button field submit-button' %>
<% end %>

app/views/pages/highlights.erb
<div id="app" data-controller="react"></div>

app/views/pages/resume.erb
<div id="app" data-controller="react"></div>

app/views/pages/specialties.erb
<div id="app" data-controller="react"></div>